(define 
    (problem shop1)
    
    (:domain shopping)
    
    (:objects 
        goodchocolate rubbishchocolate hersheys cabbage
        saurkraut rice quinoa gummyBears marshmallows book DVD game pizza - item
        randalls costco aldi walgreens home - location
        me - shopper)

    (:init 
        (stored goodchocolate randalls) 
        (stored rubbishchocolate aldi) 
        (stored hersheys costco)
        (stored saurkraut randalls) 
        (stored cabbage aldi) 
        (stored pizza costco)
        (stored gummyBears walgreens)
        (stored rice costco)
        (stored quinoa randalls)
        (stored DVD walgreens)
        (stored book costco)
        (stored pizza costco)
        (stored game walgreens)
        
        (= (entertainmentValue goodchocolate) 10)
        (= (entertainmentValue rubbishchocolate) 5)
        (= (entertainmentValue hersheys) 2)
        (= (entertainmentValue cabbage) 1)
        (= (entertainmentValue saurkraut) 5)
        (= (entertainmentValue rice) 2)
        (= (entertainmentValue quinoa) 2)
        (= (entertainmentValue gummyBears) 2)
        (= (entertainmentValue marshmallows) 7)
        (= (entertainmentValue book) 10)
        (= (entertainmentValue DVD) 8)
        (= (entertainmentValue game) 9)
        (= (entertainmentValue pizza) 5)
        
        (= (foodValue goodchocolate) 2)
        (= (foodValue rubbishchocolate) 1)
        (= (foodValue hersheys) 1)
        (= (foodValue cabbage) 10)
        (= (foodValue saurkraut) 5)
        (= (foodValue rice) 12)
        (= (foodValue quinoa) 12)
        (= (foodValue gummyBears) 1)
        (= (foodValue marshmallows) 1)
        (= (foodValue book) 0)
        (= (foodValue DVD) 0)
        (= (foodValue game) 0)
        (= (foodValue pizza) 5)
        
        (= (cost goodchocolate) 20)
        (= (cost rubbishchocolate) 5)
        (= (cost hersheys) 4)
        (= (cost cabbage) 3)
        (= (cost saurkraut) 7)
        (= (cost rice) 5)
        (= (cost quinoa) 8)
        (= (cost gummyBears) 6)
        (= (cost marshmallows) 6)
        (= (cost book) 12)
        (= (cost DVD) 30)
        (= (cost game) 40)
        (= (cost pizza) 10)
        
        (= (travelCost home costco) 8)
        (= (travelCost home walgreens) 10)
        (= (travelCost home randalls) 15)
        (= (travelCost home aldi) 5)
        (= (travelCost costco home) 8)
        (= (travelCost walgreens home) 10)
        (= (travelCost randalls home) 15)
        (= (travelCost aldi home) 5)
        (= (travelCost costco walgreens) 5)
        (= (travelCost walgreens costco) 5)
        (= (travelCost costco randalls) 6)
        (= (travelCost randalls costco) 6)
        (= (travelCost costco aldi) 8)
        (= (travelCost aldi costco) 8)
        (= (travelCost walgreens randalls) 6)
        (= (travelCost randalls walgreens) 6)
        (= (travelCost walgreens aldi) 9)
        (= (travelCost aldi walgreens) 9)
        (= (travelcost randalls aldi) 10)
        (= (travelcost aldi randalls) 10)

        (at me home)
        (= (cash me) 100)
        (= (fun me) 0)
        (= (food me) 0)
    )

    (:goal 
        (and 
            (>= (food me) 30) 
            (>= (fun me) 10) 
            (at me home)
        )
    )
)